=begin
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
=end

module Main
# @param {String} s
# @param {String} t
# @return {Character}
def find_the_difference(s, t)
  if s.empty?
    return t
  end
  char_map = Hash.new(0)

  t.split("").each do |c|
    char_map[c] += 1
  end

  s.split("").each do |c|
    char_map[c] -= 1
  end

  char_map.each do |k, v|
    return k if v == 1
  end
end 
end
